# Generated by Django 2.0.4 on 2019-10-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocoins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='available_supply',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='last_updated',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='market_cap_usd',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='max_supply',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='percent_change_1h',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='percent_change_24h',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='percent_change_7d',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='price_btc',
            field=models.DecimalField(decimal_places=7, max_digits=8),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='rank',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='slug',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='symbol',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='total_supply',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='volume_usd_24h',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
    ]
